### ISSUE TITLE
Crashes on app start

### ISSUE THREAD

**Issue by al3k87** [inventit/processing-android-serial#10]
Ive been trying to figure this out for half a day now and need help, app crashes on startup.
Application runs fine when i disable/comment this line under (no serial tho) but i can push buttons and for example trigger text etc.

`myPort = new Serial(this, Serial.list(this)[0], 9600);`

Im using the same baud rate on both devices also tried other rates, and even with arduino uno, Mega R3, pro mini 5v with FTDI but no luck.

I have checked the Vendor ID to be compatible (Arduino Mega R3) and I get the OTG pop up window where I can select the app and start when i plug my arduino to the android phone using OTG cable (Samsung S7, also testet S5).
Im running Processing 3.2.1 in Android mode with the library, is this currently unsupported?

Code example:
```
import com.yourinventit.processing.android.serial.*;
import controlP5.*;

// The serial port:
Serial myPort;  

ControlP5 cp5;

void setup()
{
  background(150);

  orientation(PORTRAIT);  // Fixes the screen size to portrait in Android
  size(displayWidth, displayHeight, P3D);
  //size(displayWidth, displayHeight);

// Start Button stuff

  cp5 = new ControlP5(this);

  // create a new button with name 'ledOn'
  cp5.addButton("ledOn")
     .setValue(0)
     .setPosition(100,200)
     .setSize(200,60)
     .setLabel("turn LED on")
     ;

  // create a new button with name 'ledOff'
  cp5.addButton("ledOff")
     .setValue(0)
     .setPosition(100,300)
     .setSize(200,60)
     .setLabel("turn LED off")
     ;

  PFont pfont = createFont("Arial",20,false); // use true/false for smooth/no-smooth
  ControlFont font = new ControlFont(pfont,241);

    cp5.getController("ledOn")
     .getCaptionLabel()
     .setFont(font)
     .toUpperCase(false)
     .setSize(24)
     ;

     cp5.getController("ledOff")
     .getCaptionLabel()
     .setFont(font)
     .toUpperCase(false)
     .setSize(24)
     ;

// End button stuff

myPort = new Serial(this, Serial.list(this)[0], 19200); // Set up serial connection 
textSize(100);
textAlign(CENTER);
text("Hello World!",width/2,height/2); //
} 

void draw() {
}

public void ledOn(int theValue) {
  background(150);
  myPort.write('1'); // write 1 to the serial connection 
}

public void ledOff(int theValue) {
  background(150);
  myPort.write('0');  // write 0 to the serial connection 
}
```

**Comment by al3k87** [comment]
I think the problem is I was using the 2013 binary, can you please update the binary to the 2016 version?

**Comment by dbaba** [comment]
Sorry for the delay. Just released the latest library. Could you please try a zip file at the [release page](https://github.com/inventit/processing-android-serial/releases/tag/0.2.0)?

**Comment by al3k87** [comment]
Awesome, Thanx I will check it out later today

**Comment by al3k87** [comment]
it works now 👍

**Comment by dbaba** [comment]
Cool!
