### ISSUE TITLE
Have you thought toask Processing project so this library could be part of processing-android github tree?

### ISSUE THREAD

**Issue by q2dg** [inventit/processing-android-serial#9]
If I'm not wrong, the only way of communication to the "outer space" Processing officially has is the "Network" library and the "Serial" library, but the latter doesn't run in Android-mode (therefore this library exist). So, to mend this "asimetry", I think a Android-like Serial library should be added to Android-mode of Processing. Why not ask? This would give a lot more visibility to your project and more people would offer his help. Thanks a lot

**Comment by dbaba** [comment]
Sorry for the late response. Yeah, I think it a good idea if processing/processing-android project support Android Serial.

The reason why I created this project is just I'd needed it then and I'd also thought it faster to create by myself than to ask someone to create it.

Unfortunately, I'm busy for my work so I don't have time to contribute the work for integrating Android Serial feature into processing/processing-android but if you or someone try to do it, feel free to ask me regarding this project.
